spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fin_trans
    username: postgres
    password: john
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
      javax:
        persistence:
          schema-generation:
            scripts:
              create-source: metadata
    hibernate:
      ddl-auto: update
